#!/bin/bash
# =============================================================================
# build-desktop-skills.sh — Build curated skills file for Claude Desktop Project
# =============================================================================
# Generates configs/claude-desktop-project-instructions.md from ECC skills.
# This file is designed to be pasted into a Claude Desktop Project as
# custom instructions (system prompt).
#
# Tiers:
#   essential  — Personal learned skills only (~22KB / ~6K tokens)
#   standard   — + All universal agents + top commands (~218KB / ~54K tokens)
#   full       — + ALL universal commands (~357KB / ~89K tokens, default)
#
# Usage:
#   scripts/build-desktop-skills.sh                   # Full tier (default)
#   scripts/build-desktop-skills.sh --tier essential   # Minimal
#   scripts/build-desktop-skills.sh --tier standard    # Balanced
#   scripts/build-desktop-skills.sh --tier full        # Everything universal
# =============================================================================
set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="$REPO_DIR/configs/claude-desktop-project-instructions.md"

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()     { echo -e "${BLUE}[SKILLS]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }

# Skill source directories
LEARNED_DIR="$HOME/.claude/skills/learned"
AGENTS_DIR="$HOME/.claude-everything-claude-code/agents"
COMMANDS_DIR="$HOME/.claude-everything-claude-code/commands"

# Parse args
TIER="full"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --tier) TIER="$2"; shift 2 ;;
        *) shift ;;
    esac
done

log "Tier: $TIER"

# =============================================================================
# Skill lists by tier
# =============================================================================

# Universal agents (non-language-specific)
UNIVERSAL_AGENTS=(
    performance-optimizer
    code-reviewer
    typescript-reviewer
    planner
    a11y-architect
    architect
    chief-of-staff
    security-reviewer
    database-reviewer
    e2e-runner
    build-error-resolver
    docs-lookup
    python-reviewer
    doc-updater
    tdd-guide
    refactor-cleaner
    seo-specialist
    code-explorer
    code-architect
    conversation-analyzer
    code-simplifier
    comment-analyzer
    silent-failure-hunter
    pr-test-analyzer
    harness-optimizer
    loop-operator
    type-design-analyzer
)

# Top coding commands (most valuable for hands-on development)
TOP_COMMANDS=(
    code-review
    tdd
    e2e
    build-fix
    feature-dev
    plan
    checkpoint
    review-pr
    refactor-clean
    test-coverage
    docs
    eval
    verify
    quality-gate
    context-budget
    model-route
    update-docs
    python-review
    prp-prd
    prp-plan
    prp-implement
    prp-pr
    prp-commit
)

# All remaining universal commands (for full tier)
ALL_UNIVERSAL_COMMANDS=(
    code-review tdd e2e build-fix feature-dev plan checkpoint review-pr
    refactor-clean test-coverage docs eval verify quality-gate context-budget
    model-route update-docs python-review prp-prd prp-plan prp-implement
    prp-pr prp-commit sessions save-session resume-session multi-execute
    multi-plan multi-workflow multi-frontend multi-backend santa-loop aside
    skill-create evolve skill-health orchestrate learn-eval pm2 jira
    instinct-import instinct-export instinct-status learn setup-pm promote
    hookify hookify-help hookify-configure hookify-list update-codemaps
    harness-audit loop-start loop-status projects devfleet prune
    prompt-optimize rules-distill agent-sort claw
)

# =============================================================================
# Build the output file
# =============================================================================
{
    cat << 'HEADER'
# Claude Desktop — Curated Skills & Instructions

> Auto-generated by ai-skillweave/scripts/build-desktop-skills.sh
> Paste this entire file into a Claude Desktop Project as custom instructions.
>
> These skills activate automatically based on context — no manual invocation needed.
> When you're doing code review, the code-reviewer skills apply. When testing, TDD skills activate. Etc.

---

HEADER

    # --- Personal Learned Skills (always included) ---
    LEARNED_COUNT=0
    if [ -d "$LEARNED_DIR" ] && ls "$LEARNED_DIR"/*.md >/dev/null 2>&1; then
        echo "## Personal Quality Standards"
        echo ""
        echo "These are custom standards extracted from your work patterns."
        echo ""
        for f in "$LEARNED_DIR"/*.md; do
            echo "---"
            echo ""
            cat "$f"
            echo ""
            LEARNED_COUNT=$((LEARNED_COUNT + 1))
        done
    fi
    log "Included $LEARNED_COUNT personal learned skills" >&2

    # --- Universal Agents (standard + full tiers) ---
    AGENT_COUNT=0
    if [ "$TIER" = "standard" ] || [ "$TIER" = "full" ]; then
        echo ""
        echo "## Agent Skills"
        echo ""
        echo "Specialized agents for code review, architecture, security, testing, and more."
        echo ""
        for name in "${UNIVERSAL_AGENTS[@]}"; do
            f="$AGENTS_DIR/$name.md"
            if [ -f "$f" ]; then
                echo "---"
                echo ""
                cat "$f"
                echo ""
                AGENT_COUNT=$((AGENT_COUNT + 1))
            fi
        done
    fi
    log "Included $AGENT_COUNT agent skills" >&2

    # --- Commands (standard: top 23, full: all universal) ---
    CMD_COUNT=0
    if [ "$TIER" = "standard" ]; then
        echo ""
        echo "## Command Skills"
        echo ""
        echo "Workflows for development tasks: code review, TDD, testing, deployment, and project planning."
        echo ""
        for name in "${TOP_COMMANDS[@]}"; do
            f="$COMMANDS_DIR/$name.md"
            if [ -f "$f" ]; then
                echo "---"
                echo ""
                cat "$f"
                echo ""
                CMD_COUNT=$((CMD_COUNT + 1))
            fi
        done
    elif [ "$TIER" = "full" ]; then
        echo ""
        echo "## Command Skills"
        echo ""
        echo "Full set of development workflows: code review, TDD, testing, deployment, project planning, session management, and more."
        echo ""
        # Deduplicate using a temp file (portable — no bash 4+ associative arrays needed)
        SEEN_FILE=$(mktemp)
        trap "rm -f $SEEN_FILE" EXIT
        for name in "${ALL_UNIVERSAL_COMMANDS[@]}"; do
            if ! grep -qx "$name" "$SEEN_FILE" 2>/dev/null; then
                echo "$name" >> "$SEEN_FILE"
                f="$COMMANDS_DIR/$name.md"
                if [ -f "$f" ]; then
                    echo "---"
                    echo ""
                    cat "$f"
                    echo ""
                    CMD_COUNT=$((CMD_COUNT + 1))
                fi
            fi
        done
        rm -f "$SEEN_FILE"
    fi
    log "Included $CMD_COUNT command skills" >&2

} > "$OUTPUT"

# Report
FILE_SIZE=$(wc -c < "$OUTPUT" | tr -d ' ')
TOKEN_EST=$((FILE_SIZE / 4))
log "Tier: $TIER"
success "Output: $OUTPUT"
success "Size: ${FILE_SIZE} bytes (~$((TOKEN_EST / 1000))K tokens)"
success "Skills: $LEARNED_COUNT personal + $AGENT_COUNT agents + $CMD_COUNT commands = $((LEARNED_COUNT + AGENT_COUNT + CMD_COUNT)) total"
echo ""
log "To use: paste contents into a Claude Desktop Project as custom instructions."
