#!/bin/bash
# =============================================================================
# setup-openclaw.sh — Configure OpenClaw for Ollama launch
# =============================================================================
# Applies the configs/openclaw.json template to ~/.openclaw/openclaw.json.
# Preserves the existing gateway auth token (machine-generated by OpenClaw).
# Enables: ollama plugin, web tools, subagent defaults with ollama model.
#
# Usage:
#   scripts/setup-openclaw.sh [--model MODEL_NAME]
#   --model : override the Ollama model (default: qwen3.5:397b-cloud)
# =============================================================================
set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE="$REPO_DIR/configs/openclaw.json"
TARGET="$HOME/.openclaw/openclaw.json"

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log()     { echo -e "${BLUE}[OPENCLAW]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Parse args
OLLAMA_MODEL="qwen3.5:397b-cloud"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --model) OLLAMA_MODEL="$2"; shift 2 ;;
        *) shift ;;
    esac
done

echo ""
echo "╔══════════════════════════════════════╗"
echo "║   OpenClaw Setup                     ║"
echo "╚══════════════════════════════════════╝"
echo ""

command -v python3 >/dev/null 2>&1 || error "python3 not found"
[ -f "$TEMPLATE" ] || error "Template not found: $TEMPLATE"

if [ ! -f "$TARGET" ]; then
    warn "~/.openclaw/openclaw.json not found. Install OpenClaw first (ollama launch openclaw --config)"
    warn "After first launch, re-run this script."
    exit 0
fi

# Backup
BACKUP="$TARGET.bak_setup_$(date +%Y%m%d_%H%M%S)"
cp "$TARGET" "$BACKUP"
success "Backup: $BACKUP"

python3 << PYEOF
import json, os

target_path = os.path.expanduser("~/.openclaw/openclaw.json")
template_path = "$TEMPLATE"
home = os.path.expanduser("~")
model = "$OLLAMA_MODEL"

with open(target_path) as f:
    current = json.load(f)

with open(template_path) as f:
    template = json.load(f)

# Substitute placeholders in template
tpl_str = json.dumps(template)
tpl_str = tpl_str.replace("{{HOME}}", home)
tpl_str = tpl_str.replace("{{OLLAMA_MODEL}}", model)
tpl = json.loads(tpl_str)

# Preserve machine-specific values from current config
existing_token = current.get("gateway", {}).get("auth", {}).get("token")
existing_meta = current.get("meta")

# Apply template sections (preserving machine-specific ones)
for key in ["agents", "commands", "models", "plugins", "session", "tools"]:
    if key in tpl:
        current[key] = tpl[key]

# Always preserve gateway token
if existing_token and "gateway" in tpl:
    tpl["gateway"]["auth"]["token"] = existing_token
    current["gateway"] = tpl["gateway"]

# Preserve meta
if existing_meta:
    current["meta"] = existing_meta

with open(target_path, "w") as f:
    json.dump(current, f, indent=2)

print(f"Model set to: ollama/{model}")
print(f"Web tools: fetch={current['tools']['web']['fetch']['enabled']}, search={current['tools']['web']['search']['enabled']}")
print(f"Ollama plugin: {current['plugins']['entries']['ollama']['enabled']}")
print(f"Gateway token: preserved ({existing_token[:8]}...)" if existing_token else "Gateway token: not found")
PYEOF

success "OpenClaw config applied"
echo ""
log "Restart OpenClaw (or run: ollama launch openclaw) for changes to take effect."
echo ""
